# Generated by Django 4.2.19 on 2025-03-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_options_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='order',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
