# Generated by Django 4.2.19 on 2025-03-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_data_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Заголовок'), (1, 'Текст')]),
        ),
    ]
