# Generated by Django 4.2.19 on 2025-03-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_data_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
