# Generated by Django 4.2.19 on 2025-03-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_data_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
